# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
  versioning:
    enabled: true
    default_version: 1
    resolvers:
      query:
        enabled: true
        parameter_name: version
      custom_header:
        enabled: true
        header_name: X-Accept-Version
    guessing_order:
      - query
      - custom_header
  view: ~
  format_listener:
    rules:
      - { path: '^/', priorities: ['json'], fallback_format: json, prefer_extension: false }